services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - GROUPNAME=${USER}
        - UID=1000
        - GID=1000
    shm_size: 2g
    command: sleep infinity
    environment:
      - LANG=C.UTF-8
      - UNITY_DATASET_FILE_ID=${UNITY_DATASET_FILE_ID}
      - UNITY_DATASET_FILE_NAME=${UNITY_DATASET_FILE_NAME}
    volumes:
      - "./src:/home/${USER}/deeplab-custom-dataset/src"
    working_dir: /home/${USER}/deeplab-custom-dataset/src
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
